### ISSUE TITLE
After login an error related to not found module appears

### ISSUE THREAD

**Issue by Eshva** [Eshva/EveHQ-NG.Prototype#26]
## Steps to reproduce
1. Open application and ensure it's not logged in.
2. Press Login button in application. An authorization page opens in a browser.
3. Authorize the application.

## Bug
An error message appears: ```The `logger` option function in electron-unhandled threw an error```
<details><summary><b>Detailed error log</b></summary>
<p>

```
[Window Title]
Error

[Main Instruction]
The `logger` option function in electron-unhandled threw an error

[Content]
Error: Cannot find module '../net'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Program Files\EveHQ NG\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as net] (C:\Program Files\EveHQ NG\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at Object.logExceptionToApi [as logger] (C:\Program Files\EveHQ NG\resources\app.asar\main.js:184:32)
    at handleError (C:\Program Files\EveHQ NG\resources\app.asar\node_modules\electron-unhandled\index.js:28:12)
    at process.on.err (C:\Program Files\EveHQ NG\resources\app.asar\node_modules\electron-unhandled\index.js:70:4)
    at emitOne (events.js:120:20)

[OK]

```

</p>
</details>

## Expected
* No error appears.
* Application successfully authorized and displays the character page.

**Comment by Eshva** [comment]
Seams like it relates to singleton applications. If the application uses ```process.quit()``` to close the second instance, ```app.ready``` event handler called anyway. To mitigate it we need to use ```process.exit()``` instead. This way no any event handlers will be called.

[A relevant bug report: Cannot find module '../screen'](https://github.com/electron/electron/issues/8862)
[The solution](https://github.com/electron/electron/issues/8862#issuecomment-294303518)
